### ISSUE TITLE
Error under 1.8.7 compatible

### ISSUE THREAD

**Issue by knaveofdiamonds** [d11wtq/whittle#2]
Trying to run an example (i.e. mathematician) under 1.8.7 raises the following error:

/gems/whittle-0.0.8/lib/whittle/terminal.rb:30:in `match': wrong number of arguments (2 for 1) (ArgumentError)

Don't know if you have any interest in supporting this under 1.8.7.

**Comment by d11wtq** [comment]
I know this is an old issue. There are no plans to support 1.8, which is now very old.
